/**
 * Bangla display labels for merchant categories.
 *
 * Categories are stored in `public.merchant_categories` with English labels.
 * When the app is in Bangla mode we translate the labels client-side so the
 * apply / edit dropdowns are readable to Bangla users without a schema change.
 *
 * Every current DB `name` MUST have an entry here — the merchant apply flow
 * lists 141 categories and users see mixed English/Bangla otherwise.
 * Unknown names fall back to their English label — never render nothing.
 */
const MAP: Record<string, string> = {
  // Live DB categories (public.merchant_categories.name)
  accounting: "হিসাবরক্ষণ ও কর",
  agriculture: "কৃষি",
  airline: "এয়ারলাইন",
  amusement_park: "বিনোদন ও থিম পার্ক",
  architecture: "স্থাপত্য",
  art_gallery: "আর্ট গ্যালারি",
  automotive: "অটোমোটিভ",
  ayurveda: "আয়ুর্বেদ ও বিকল্প চিকিৎসা",
  baby_products: "শিশু পণ্য",
  bakery: "বেকারি ও মিষ্টান্ন",
  beauty: "সৌন্দর্য ও সুস্থতা",
  beverage: "পানীয় ও জুস",
  bookshop: "বইয়ের দোকান ও লাইব্রেরি",
  cable_tv: "কেবল টিভি ও ডিটিএইচ",
  car_rental: "গাড়ি ভাড়া",
  catering: "ক্যাটারিং",
  charity: "দাতব্য ও দান",
  cinema: "সিনেমা ও থিয়েটার",
  cleaning_services: "পরিষ্কার সেবা",
  cloud_hosting: "ক্লাউড ও হোস্টিং",
  cloud_kitchen: "ক্লাউড কিচেন",
  club: "ক্লাব ও বিনোদন",
  coaching: "কোচিং ও টিউশন",
  college: "কলেজ ও বিশ্ববিদ্যালয়",
  construction: "নির্মাণ",
  consulting: "কনসালটিং",
  cooperative: "সমবায় সমিতি",
  cosmetics: "প্রসাধনী",
  courier: "কুরিয়ার ও পার্সেল",
  customs_clearing: "কাস্টমস ক্লিয়ারিং",
  cybersecurity: "সাইবার নিরাপত্তা",
  dairy: "দুগ্ধ ও ফ্রোজেন খাবার",
  data_analytics: "ডেটা অ্যানালিটিক্স",
  dental: "ডেন্টাল কেয়ার",
  diagnostic: "ডায়াগনস্টিক ও ল্যাব",
  driving_school: "ড্রাইভিং স্কুল",
  ecommerce: "ই-কমার্স",
  education: "শিক্ষা",
  electrical_services: "বৈদ্যুতিক সেবা",
  electricity: "বিদ্যুৎ ও ইউটিলিটি",
  electronics: "ইলেকট্রনিক্স",
  engineering: "প্রকৌশল",
  entertainment: "বিনোদন",
  event_management: "ইভেন্ট ম্যানেজমেন্ট",
  eye_care: "চক্ষু সেবা ও অপটিক্যাল",
  farm_equipment: "কৃষি যন্ত্রপাতি",
  fashion: "ফ্যাশন ও পোশাক",
  fintech: "ফিনটেক",
  fishing: "মৎস্য ও জলজ চাষ",
  food: "খাদ্য ও পানীয়",
  freight: "মালামাল ও কার্গো",
  furniture: "আসবাবপত্র ও গৃহসজ্জা",
  gaming: "গেমিং ও ই-স্পোর্টস",
  gardening: "বাগান ও ল্যান্ডস্কেপিং",
  gas_station: "গ্যাস স্টেশন ও জ্বালানি",
  gift_shop: "উপহারের দোকান",
  government: "সরকারি",
  grocery: "মুদি",
  gym: "জিম ও ফিটনেস সেন্টার",
  handicraft: "হস্তশিল্প ও কারুশিল্প",
  hardware: "হার্ডওয়্যার ও যন্ত্রপাতি",
  healthcare: "স্বাস্থ্যসেবা",
  home_repair: "গৃহ মেরামত ও রক্ষণাবেক্ষণ",
  hospital: "হাসপাতাল ও ক্লিনিক",
  hostel: "হোস্টেল ও গেস্ট হাউস",
  hotel: "হোটেল ও রিসোর্ট",
  import_export: "আমদানি ও রপ্তানি",
  insurance: "বীমা",
  interior_design: "ইন্টেরিয়র ডিজাইন",
  isp: "ইন্টারনেট সেবা প্রদানকারী",
  it_services: "আইটি সেবা ও সফটওয়্যার",
  jewelry: "গহনা ও ঘড়ি",
  language_school: "ভাষা শিক্ষা",
  laundry: "লন্ড্রি ও ড্রাই ক্লিনিং",
  leather: "চামড়া ও জুতা",
  legal: "আইনি সেবা",
  logistics: "লজিস্টিকস ও ডেলিভারি",
  manufacturing: "উৎপাদন",
  marketing: "বিপণন ও বিজ্ঞাপন",
  meat_fish: "মাংস ও মাছ",
  media: "গণমাধ্যম ও প্রকাশনা",
  medical_equipment: "চিকিৎসা সরঞ্জাম",
  mental_health: "মানসিক স্বাস্থ্য ও কাউন্সেলিং",
  microfinance: "ক্ষুদ্রঋণ",
  mining: "খনি ও খনিজ",
  mobile_app: "মোবাইল অ্যাপ ডেভেলপমেন্ট",
  mobile_operator: "মোবাইল অপারেটর",
  moving_services: "মুভিং ও রিলোকেশন",
  museum: "জাদুঘর ও ঐতিহ্য",
  music: "সঙ্গীত ও অডিও",
  ngo: "এনজিও / অলাভজনক",
  online_learning: "অনলাইন শিক্ষা",
  organic_food: "অর্গানিক ও স্বাস্থ্যকর খাবার",
  other: "অন্যান্য",
  painting: "রঙ ও সাজসজ্জা",
  pest_control: "পেস্ট কন্ট্রোল",
  pet_care: "পোষা প্রাণী ও পশু চিকিৎসা",
  pharmacy: "ফার্মেসি",
  photography: "ফটোগ্রাফি ও ভিডিওগ্রাফি",
  physiotherapy: "ফিজিওথেরাপি",
  plumbing: "প্লাম্বিং",
  poultry: "পোল্ট্রি ও গবাদি পশু",
  printing: "প্রিন্টিং ও প্যাকেজিং",
  real_estate: "রিয়েল এস্টেট",
  real_estate_agent: "রিয়েল এস্টেট এজেন্সি",
  recycling: "পুনর্ব্যবহার",
  religious: "ধর্মীয় সংস্থা",
  remittance: "রেমিট্যান্স সেবা",
  restaurant: "রেস্টুরেন্ট",
  retail: "খুচরা",
  ride_sharing: "রাইড শেয়ারিং",
  salon: "সেলুন ও নাপিতের দোকান",
  school: "স্কুল",
  security_services: "নিরাপত্তা সেবা",
  seeds_fertilizer: "বীজ ও সার",
  services: "সেবা",
  shipping: "শিপিং ও নৌপরিবহন",
  solar_energy: "সৌর ও নবায়নযোগ্য শক্তি",
  spa: "স্পা ও ম্যাসাজ",
  sports: "খেলাধুলা ও ফিটনেস",
  stationery: "স্টেশনারি ও অফিস সরবরাহ",
  stock_broker: "স্টক ব্রোকার ও ট্রেডিং",
  street_food: "স্ট্রিট ফুড ও নাস্তা",
  supermarket: "সুপারমার্কেট ও ডিপার্টমেন্টাল",
  swimming: "সাঁতার ও জলক্রীড়া",
  tea_coffee: "চা ও কফি শপ",
  telecom: "টেলিকম",
  textile: "টেক্সটাইল ও গার্মেন্টস",
  tour_operator: "ট্যুর অপারেটর",
  toys: "খেলনা ও শিশু",
  training_institute: "প্রশিক্ষণ ইনস্টিটিউট",
  transportation: "পরিবহন",
  travel: "ভ্রমণ ও পর্যটন",
  travel_agency: "ট্রাভেল এজেন্সি",
  warehouse: "গুদাম ও সংরক্ষণ",
  waste_management: "বর্জ্য ব্যবস্থাপনা",
  water_supply: "পানি সরবরাহ",
  web_development: "ওয়েব ডেভেলপমেন্ট",
  wedding_services: "বিবাহ সেবা",
  wholesale: "পাইকারি ও পরিবেশন",
  yoga: "যোগব্যায়াম ও ধ্যান",

  // Legacy / alternate keys kept for backward compatibility with older data.
  saloon: "সেলুন ও নাপিতের দোকান",
  fish: "মাছ",
  vegetables: "শাকসবজি",
  fruits: "ফলমূল",
  bank: "ব্যাংক",
  mobile_recharge: "মোবাইল রিচার্জ",
  utility: "ইউটিলিটি",
  cafe: "ক্যাফে",
  butcher: "কসাই",
  pet: "পোষা প্রাণী",
  garden: "বাগান",
  art: "শিল্প ও কারুকাজ",
  software: "সফটওয়্যার",
  hosting: "হোস্টিং",
  training: "প্রশিক্ষণ",
  event: "ইভেন্ট",
  wedding: "বিয়ে",
  florist: "ফুলের দোকান",
  gift: "উপহার",
  cleaning: "পরিষ্কার সেবা",
  security: "নিরাপত্তা",
  repair: "মেরামত",
  electrical: "বৈদ্যুতিক",
  paint: "রঙ",
  rice_mill: "চাল কল",
  tea_stall: "চা স্টল",
  fisheries: "মৎস্য",
  nursery: "নার্সারি",
  online_store: "অনলাইন স্টোর",
  freelance: "ফ্রিল্যান্স",
};

export function bnCategoryLabel(name: string | null | undefined, fallback: string): string {
  if (!name) return fallback;
  return MAP[name] ?? fallback;
}
