/**
 * Bangla display labels for merchant categories.
 *
 * Categories are stored in `public.merchant_categories` with English labels.
 * When the app is in Bangla mode we translate the labels client-side so the
 * apply / edit dropdowns are readable to Bangla users without a schema change.
 *
 * Unknown names fall back to their English label — never render nothing.
 */
const MAP: Record<string, string> = {
  retail: "খুচরা",
  food: "খাদ্য ও পানীয়",
  ecommerce: "ই-কমার্স",
  services: "সেবা",
  healthcare: "স্বাস্থ্যসেবা",
  education: "শিক্ষা",
  travel: "ভ্রমণ ও পর্যটন",
  electronics: "ইলেকট্রনিক্স",
  fashion: "ফ্যাশন ও পোশাক",
  grocery: "মুদি",
  pharmacy: "ফার্মেসি",
  restaurant: "রেস্টুরেন্ট",
  transportation: "পরিবহন",
  real_estate: "রিয়েল এস্টেট",
  agriculture: "কৃষি",
  manufacturing: "উৎপাদন",
  telecom: "টেলিকম",
  entertainment: "বিনোদন",
  beauty: "সৌন্দর্য ও সুস্থতা",
  sports: "খেলাধুলা ও ফিটনেস",
  logistics: "লজিস্টিকস ও ডেলিভারি",
  consulting: "কনসালটিং",
  ngo: "এনজিও / অলাভজনক",
  government: "সরকারি",
  fintech: "ফিনটেক",
  insurance: "বীমা",
  legal: "আইনি সেবা",
  accounting: "হিসাবরক্ষণ ও কর",
  marketing: "বিপণন ও বিজ্ঞাপন",
  media: "গণমাধ্যম ও প্রকাশনা",
  photography: "ফটোগ্রাফি ও ভিডিওগ্রাফি",
  printing: "প্রিন্টিং ও প্যাকেজিং",
  construction: "নির্মাণ",
  interior_design: "ইন্টেরিয়র ডিজাইন",
  architecture: "স্থাপত্য",
  engineering: "প্রকৌশল",
  automotive: "অটোমোটিভ",
  car_rental: "গাড়ি ভাড়া",
  ride_sharing: "রাইড শেয়ারিং",
  courier: "কুরিয়ার ও পার্সেল",
  freight: "মালামাল পরিবহন",
  warehouse: "গুদাম ও সংরক্ষণ",
  textile: "টেক্সটাইল ও গার্মেন্টস",
  leather: "চামড়া ও জুতা",
  jewelry: "গহনা ও ঘড়ি",
  cosmetics: "প্রসাধনী",
  furniture: "আসবাবপত্র ও গৃহসজ্জা",
  hardware: "হার্ডওয়্যার ও যন্ত্রপাতি",
  stationery: "স্টেশনারি ও অফিস সরবরাহ",
  bookshop: "বইয়ের দোকান ও লাইব্রেরি",
  saloon: "সেলুন",
  salon: "সেলুন",
  spa: "স্পা",
  gym: "জিম",
  hotel: "হোটেল",
  cafe: "ক্যাফে",
  bakery: "বেকারি",
  butcher: "কসাই",
  fish: "মাছ",
  vegetables: "শাকসবজি",
  fruits: "ফলমূল",
  dairy: "দুগ্ধজাত",
  bank: "ব্যাংক",
  mobile_recharge: "মোবাইল রিচার্জ",
  utility: "ইউটিলিটি",
  charity: "দাতব্য",
  religious: "ধর্মীয়",
  toys: "খেলনা",
  pet: "পোষা প্রাণী",
  garden: "বাগান",
  art: "শিল্প ও কারুকাজ",
  music: "সঙ্গীত",
  gaming: "গেমিং",
  software: "সফটওয়্যার",
  hosting: "হোস্টিং",
  training: "প্রশিক্ষণ",
  coaching: "কোচিং",
  event: "ইভেন্ট",
  wedding: "বিয়ে",
  florist: "ফুলের দোকান",
  gift: "উপহার",
  laundry: "লন্ড্রি",
  cleaning: "পরিষ্কার সেবা",
  security: "নিরাপত্তা",
  repair: "মেরামত",
  plumbing: "প্লাম্বিং",
  electrical: "বৈদ্যুতিক",
  paint: "রঙ",
  rice_mill: "চাল কল",
  tea_stall: "চা স্টল",
  poultry: "পোল্ট্রি",
  fisheries: "মৎস্য",
  nursery: "নার্সারি",
  online_store: "অনলাইন স্টোর",
  freelance: "ফ্রিল্যান্স",
  other: "অন্যান্য",
};

export function bnCategoryLabel(name: string | null | undefined, fallback: string): string {
  if (!name) return fallback;
  return MAP[name] ?? fallback;
}
