project_id = "lmgsxyzytssddijjxbzc"

[functions.bkash-payment]
verify_jwt = false

[functions.nagad-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.test-recharge-api]
verify_jwt = false

[functions.process-recharge]
verify_jwt = false

[functions.kyc-ocr]
verify_jwt = false

[functions.kyc-face-match]
verify_jwt = false

[functions.kyc-notify]
verify_jwt = false

[functions.validate-device]
verify_jwt = false

[functions.asthapay-payment]
verify_jwt = false

[functions.soft-delete-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.auto-purge-deactivated]
verify_jwt = false

[functions.manage-gateway-config]
verify_jwt = false

[functions.send-team-credentials]
verify_jwt = false

[functions.merchant-payment-webhook]
verify_jwt = false

[functions.retry-failed-webhooks]
verify_jwt = false

[functions.merchant-payment-api]
verify_jwt = false

[functions.checkout-pay]
verify_jwt = false

[functions.admin-reset-pin]
verify_jwt = false

[functions.apply-coupon]
verify_jwt = false

[functions.product-recommendations]
verify_jwt = false

[functions.mfs-incoming-webhook]
verify_jwt = false

[functions.notify-api-access-decision]
verify_jwt = false
