
CREATE TABLE public.merchant_categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text UNIQUE NOT NULL,
  label text NOT NULL,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.merchant_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read categories" ON public.merchant_categories FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage categories" ON public.merchant_categories FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin'::app_role)) WITH CHECK (public.has_role(auth.uid(), 'admin'::app_role));

INSERT INTO public.merchant_categories (name, label, sort_order) VALUES
  ('retail', 'Retail', 1),
  ('food', 'Food & Beverage', 2),
  ('ecommerce', 'E-Commerce', 3),
  ('services', 'Services', 4),
  ('healthcare', 'Healthcare', 5),
  ('education', 'Education', 6),
  ('travel', 'Travel & Tourism', 7),
  ('electronics', 'Electronics', 8),
  ('fashion', 'Fashion & Clothing', 9),
  ('grocery', 'Grocery', 10),
  ('pharmacy', 'Pharmacy', 11),
  ('restaurant', 'Restaurant', 12),
  ('transportation', 'Transportation', 13),
  ('real_estate', 'Real Estate', 14),
  ('agriculture', 'Agriculture', 15),
  ('manufacturing', 'Manufacturing', 16),
  ('telecom', 'Telecom', 17),
  ('entertainment', 'Entertainment', 18),
  ('beauty', 'Beauty & Wellness', 19),
  ('sports', 'Sports & Fitness', 20),
  ('logistics', 'Logistics & Delivery', 21),
  ('consulting', 'Consulting', 22),
  ('ngo', 'NGO / Non-Profit', 23),
  ('government', 'Government', 24),
  ('fintech', 'Fintech', 25),
  ('insurance', 'Insurance', 26),
  ('legal', 'Legal Services', 27),
  ('accounting', 'Accounting & Tax', 28),
  ('marketing', 'Marketing & Advertising', 29),
  ('media', 'Media & Publishing', 30),
  ('photography', 'Photography & Videography', 31),
  ('printing', 'Printing & Packaging', 32),
  ('construction', 'Construction', 33),
  ('interior_design', 'Interior Design', 34),
  ('architecture', 'Architecture', 35),
  ('engineering', 'Engineering', 36),
  ('automotive', 'Automotive', 37),
  ('car_rental', 'Car Rental', 38),
  ('ride_sharing', 'Ride Sharing', 39),
  ('courier', 'Courier & Parcel', 40),
  ('freight', 'Freight & Cargo', 41),
  ('warehouse', 'Warehouse & Storage', 42),
  ('textile', 'Textile & Garments', 43),
  ('leather', 'Leather & Footwear', 44),
  ('jewelry', 'Jewelry & Watches', 45),
  ('cosmetics', 'Cosmetics', 46),
  ('furniture', 'Furniture & Home Decor', 47),
  ('hardware', 'Hardware & Tools', 48),
  ('stationery', 'Stationery & Office Supplies', 49),
  ('bookshop', 'Bookshop & Library', 50),
  ('pet_care', 'Pet Care & Veterinary', 51),
  ('laundry', 'Laundry & Dry Cleaning', 52),
  ('salon', 'Salon & Barbershop', 53),
  ('spa', 'Spa & Massage', 54),
  ('gym', 'Gym & Fitness Center', 55),
  ('yoga', 'Yoga & Meditation', 56),
  ('swimming', 'Swimming & Aquatics', 57),
  ('club', 'Club & Recreation', 58),
  ('hotel', 'Hotel & Resort', 59),
  ('hostel', 'Hostel & Guest House', 60),
  ('airline', 'Airline', 61),
  ('travel_agency', 'Travel Agency', 62),
  ('tour_operator', 'Tour Operator', 63),
  ('event_management', 'Event Management', 64),
  ('catering', 'Catering', 65),
  ('bakery', 'Bakery & Confectionery', 66),
  ('dairy', 'Dairy & Frozen Foods', 67),
  ('meat_fish', 'Meat & Fish', 68),
  ('organic_food', 'Organic & Health Food', 69),
  ('beverage', 'Beverage & Juice', 70),
  ('tea_coffee', 'Tea & Coffee Shop', 71),
  ('street_food', 'Street Food & Snacks', 72),
  ('cloud_kitchen', 'Cloud Kitchen', 73),
  ('hospital', 'Hospital & Clinic', 74),
  ('dental', 'Dental Care', 75),
  ('eye_care', 'Eye Care & Optical', 76),
  ('diagnostic', 'Diagnostic & Lab', 77),
  ('physiotherapy', 'Physiotherapy', 78),
  ('mental_health', 'Mental Health & Counseling', 79),
  ('ayurveda', 'Ayurveda & Alternative Medicine', 80),
  ('medical_equipment', 'Medical Equipment', 81),
  ('school', 'School', 82),
  ('college', 'College & University', 83),
  ('coaching', 'Coaching & Tutoring', 84),
  ('online_learning', 'Online Learning', 85),
  ('training_institute', 'Training Institute', 86),
  ('driving_school', 'Driving School', 87),
  ('language_school', 'Language School', 88),
  ('it_services', 'IT Services & Software', 89),
  ('web_development', 'Web Development', 90),
  ('mobile_app', 'Mobile App Development', 91),
  ('data_analytics', 'Data Analytics', 92),
  ('cybersecurity', 'Cybersecurity', 93),
  ('cloud_hosting', 'Cloud & Hosting', 94),
  ('isp', 'Internet Service Provider', 95),
  ('cable_tv', 'Cable TV & DTH', 96),
  ('mobile_operator', 'Mobile Operator', 97),
  ('solar_energy', 'Solar & Renewable Energy', 98),
  ('gas_station', 'Gas Station & Fuel', 99),
  ('electricity', 'Electricity & Utility', 100),
  ('water_supply', 'Water Supply', 101),
  ('waste_management', 'Waste Management', 102),
  ('recycling', 'Recycling', 103),
  ('mining', 'Mining & Minerals', 104),
  ('fishing', 'Fishing & Aquaculture', 105),
  ('poultry', 'Poultry & Livestock', 106),
  ('seeds_fertilizer', 'Seeds & Fertilizer', 107),
  ('farm_equipment', 'Farm Equipment', 108),
  ('handicraft', 'Handicraft & Artisan', 109),
  ('charity', 'Charity & Donation', 110),
  ('religious', 'Religious Organization', 111),
  ('cooperative', 'Cooperative Society', 112),
  ('microfinance', 'Microfinance', 113),
  ('remittance', 'Remittance Service', 114),
  ('stock_broker', 'Stock Broker & Trading', 115),
  ('real_estate_agent', 'Real Estate Agency', 116),
  ('security_services', 'Security Services', 117),
  ('cleaning_services', 'Cleaning Services', 118),
  ('home_repair', 'Home Repair & Maintenance', 119),
  ('plumbing', 'Plumbing', 120),
  ('electrical_services', 'Electrical Services', 121),
  ('painting', 'Painting & Decoration', 122),
  ('gardening', 'Gardening & Landscaping', 123),
  ('pest_control', 'Pest Control', 124),
  ('moving_services', 'Moving & Relocation', 125),
  ('wedding_services', 'Wedding Services', 126),
  ('music', 'Music & Audio', 127),
  ('gaming', 'Gaming & eSports', 128),
  ('cinema', 'Cinema & Theater', 129),
  ('art_gallery', 'Art Gallery', 130),
  ('museum', 'Museum & Heritage', 131),
  ('amusement_park', 'Amusement & Theme Park', 132),
  ('toys', 'Toys & Kids', 133),
  ('baby_products', 'Baby Products', 134),
  ('gift_shop', 'Gift Shop & Novelty', 135),
  ('supermarket', 'Supermarket & Departmental', 136),
  ('wholesale', 'Wholesale & Distribution', 137),
  ('import_export', 'Import & Export', 138),
  ('customs_clearing', 'Customs Clearing', 139),
  ('shipping', 'Shipping & Maritime', 140),
  ('other', 'Other', 999);
