-- Create upazilas table
CREATE TABLE IF NOT EXISTS public.upazilas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  division text NOT NULL,
  district text NOT NULL,
  upazila text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (division, district, upazila)
);

GRANT SELECT ON public.upazilas TO anon, authenticated;
GRANT ALL ON public.upazilas TO service_role;

ALTER TABLE public.upazilas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read upazilas" ON public.upazilas;
CREATE POLICY "Anyone can read upazilas" ON public.upazilas FOR SELECT USING (true);

CREATE INDEX IF NOT EXISTS idx_upazilas_div_dist ON public.upazilas (division, district);

-- Add division / upazila to agents
ALTER TABLE public.agents
  ADD COLUMN IF NOT EXISTS division text,
  ADD COLUMN IF NOT EXISTS upazila text;

INSERT INTO public.upazilas (division, district, upazila) VALUES
('Chittagong','Comilla','Debidwar'),('Chittagong','Comilla','Barura'),('Chittagong','Comilla','Brahmanpara'),('Chittagong','Comilla','Chandina'),('Chittagong','Comilla','Chauddagram'),('Chittagong','Comilla','Daudkandi'),('Chittagong','Comilla','Homna'),('Chittagong','Comilla','Laksam'),('Chittagong','Comilla','Muradnagar'),('Chittagong','Comilla','Nangalkot'),('Chittagong','Comilla','Comilla Sadar'),('Chittagong','Comilla','Meghna'),('Chittagong','Comilla','Monohargonj'),('Chittagong','Comilla','Sadarsouth'),('Chittagong','Comilla','Titas'),('Chittagong','Comilla','Burichang'),('Chittagong','Comilla','Lalmai'),
('Chittagong','Feni','Chhagalnaiya'),('Chittagong','Feni','Feni Sadar'),('Chittagong','Feni','Sonagazi'),('Chittagong','Feni','Fulgazi'),('Chittagong','Feni','Parshuram'),('Chittagong','Feni','Daganbhuiyan'),
('Chittagong','Brahmanbaria','Brahmanbaria Sadar'),('Chittagong','Brahmanbaria','Kasba'),('Chittagong','Brahmanbaria','Nasirnagar'),('Chittagong','Brahmanbaria','Sarail'),('Chittagong','Brahmanbaria','Ashuganj'),('Chittagong','Brahmanbaria','Akhaura'),('Chittagong','Brahmanbaria','Nabinagar'),('Chittagong','Brahmanbaria','Bancharampur'),('Chittagong','Brahmanbaria','Bijoynagar'),
('Chittagong','Rangamati','Rangamati Sadar'),('Chittagong','Rangamati','Kaptai'),('Chittagong','Rangamati','Kawkhali'),('Chittagong','Rangamati','Baghaichari'),('Chittagong','Rangamati','Barkal'),('Chittagong','Rangamati','Langadu'),('Chittagong','Rangamati','Rajasthali'),('Chittagong','Rangamati','Belaichari'),('Chittagong','Rangamati','Juraichari'),('Chittagong','Rangamati','Naniarchar'),
('Chittagong','Noakhali','Noakhali Sadar'),('Chittagong','Noakhali','Companiganj'),('Chittagong','Noakhali','Begumganj'),('Chittagong','Noakhali','Hatia'),('Chittagong','Noakhali','Subarnachar'),('Chittagong','Noakhali','Kabirhat'),('Chittagong','Noakhali','Senbug'),('Chittagong','Noakhali','Chatkhil'),('Chittagong','Noakhali','Sonaimori'),
('Chittagong','Chandpur','Haimchar'),('Chittagong','Chandpur','Kachua'),('Chittagong','Chandpur','Shahrasti'),('Chittagong','Chandpur','Chandpur Sadar'),('Chittagong','Chandpur','Matlab South'),('Chittagong','Chandpur','Hajiganj'),('Chittagong','Chandpur','Matlab North'),('Chittagong','Chandpur','Faridgonj'),
('Chittagong','Lakshmipur','Lakshmipur Sadar'),('Chittagong','Lakshmipur','Kamalnagar'),('Chittagong','Lakshmipur','Raipur'),('Chittagong','Lakshmipur','Ramgati'),('Chittagong','Lakshmipur','Ramganj'),
('Chittagong','Chattogram','Rangunia'),('Chittagong','Chattogram','Sitakunda'),('Chittagong','Chattogram','Mirsharai'),('Chittagong','Chattogram','Patiya'),('Chittagong','Chattogram','Sandwip'),('Chittagong','Chattogram','Banshkhali'),('Chittagong','Chattogram','Boalkhali'),('Chittagong','Chattogram','Anwara'),('Chittagong','Chattogram','Chandanaish'),('Chittagong','Chattogram','Satkania'),('Chittagong','Chattogram','Lohagara'),('Chittagong','Chattogram','Hathazari'),('Chittagong','Chattogram','Fatikchhari'),('Chittagong','Chattogram','Raozan'),('Chittagong','Chattogram','Karnafuli'),
('Chittagong','Coxsbazar','Coxsbazar Sadar'),('Chittagong','Coxsbazar','Chakaria'),('Chittagong','Coxsbazar','Kutubdia'),('Chittagong','Coxsbazar','Ukhiya'),('Chittagong','Coxsbazar','Moheshkhali'),('Chittagong','Coxsbazar','Pekua'),('Chittagong','Coxsbazar','Ramu'),('Chittagong','Coxsbazar','Teknaf'),('Chittagong','Coxsbazar','Eidgaon'),
('Chittagong','Khagrachhari','Khagrachhari Sadar'),('Chittagong','Khagrachhari','Dighinala'),('Chittagong','Khagrachhari','Panchari'),('Chittagong','Khagrachhari','Laxmichhari'),('Chittagong','Khagrachhari','Mohalchari'),('Chittagong','Khagrachhari','Manikchari'),('Chittagong','Khagrachhari','Ramgarh'),('Chittagong','Khagrachhari','Matiranga'),('Chittagong','Khagrachhari','Guimara'),
('Chittagong','Bandarban','Bandarban Sadar'),('Chittagong','Bandarban','Alikadam'),('Chittagong','Bandarban','Naikhongchhari'),('Chittagong','Bandarban','Rowangchhari'),('Chittagong','Bandarban','Lama'),('Chittagong','Bandarban','Ruma'),('Chittagong','Bandarban','Thanchi'),
('Rajshahi','Sirajganj','Belkuchi'),('Rajshahi','Sirajganj','Chauhali'),('Rajshahi','Sirajganj','Kamarkhand'),('Rajshahi','Sirajganj','Kazipur'),('Rajshahi','Sirajganj','Raigonj'),('Rajshahi','Sirajganj','Shahjadpur'),('Rajshahi','Sirajganj','Sirajganj Sadar'),('Rajshahi','Sirajganj','Tarash'),('Rajshahi','Sirajganj','Ullapara'),
('Rajshahi','Pabna','Sujanagar'),('Rajshahi','Pabna','Ishurdi'),('Rajshahi','Pabna','Bhangura'),('Rajshahi','Pabna','Pabna Sadar'),('Rajshahi','Pabna','Bera'),('Rajshahi','Pabna','Atghoria'),('Rajshahi','Pabna','Chatmohar'),('Rajshahi','Pabna','Santhia'),('Rajshahi','Pabna','Faridpur'),
('Rajshahi','Bogura','Kahaloo'),('Rajshahi','Bogura','Bogra Sadar'),('Rajshahi','Bogura','Shariakandi'),('Rajshahi','Bogura','Shajahanpur'),('Rajshahi','Bogura','Dupchanchia'),('Rajshahi','Bogura','Adamdighi'),('Rajshahi','Bogura','Nondigram'),('Rajshahi','Bogura','Sonatala'),('Rajshahi','Bogura','Dhunot'),('Rajshahi','Bogura','Gabtali'),('Rajshahi','Bogura','Sherpur'),('Rajshahi','Bogura','Shibganj'),
('Rajshahi','Rajshahi','Paba'),('Rajshahi','Rajshahi','Durgapur'),('Rajshahi','Rajshahi','Mohonpur'),('Rajshahi','Rajshahi','Charghat'),('Rajshahi','Rajshahi','Puthia'),('Rajshahi','Rajshahi','Bagha'),('Rajshahi','Rajshahi','Godagari'),('Rajshahi','Rajshahi','Tanore'),('Rajshahi','Rajshahi','Bagmara'),
('Rajshahi','Natore','Natore Sadar'),('Rajshahi','Natore','Singra'),('Rajshahi','Natore','Baraigram'),('Rajshahi','Natore','Bagatipara'),('Rajshahi','Natore','Lalpur'),('Rajshahi','Natore','Gurudaspur'),('Rajshahi','Natore','Naldanga'),
('Rajshahi','Joypurhat','Akkelpur'),('Rajshahi','Joypurhat','Kalai'),('Rajshahi','Joypurhat','Khetlal'),('Rajshahi','Joypurhat','Panchbibi'),('Rajshahi','Joypurhat','Joypurhat Sadar'),
('Rajshahi','Chapainawabganj','Chapainawabganj Sadar'),('Rajshahi','Chapainawabganj','Gomostapur'),('Rajshahi','Chapainawabganj','Nachol'),('Rajshahi','Chapainawabganj','Bholahat'),('Rajshahi','Chapainawabganj','Shibganj'),
('Rajshahi','Naogaon','Mohadevpur'),('Rajshahi','Naogaon','Badalgachi'),('Rajshahi','Naogaon','Patnitala'),('Rajshahi','Naogaon','Dhamoirhat'),('Rajshahi','Naogaon','Niamatpur'),('Rajshahi','Naogaon','Manda'),('Rajshahi','Naogaon','Atrai'),('Rajshahi','Naogaon','Raninagar'),('Rajshahi','Naogaon','Naogaon Sadar'),('Rajshahi','Naogaon','Porsha'),('Rajshahi','Naogaon','Sapahar'),
('Khulna','Jashore','Manirampur'),('Khulna','Jashore','Abhaynagar'),('Khulna','Jashore','Bagherpara'),('Khulna','Jashore','Chougachha'),('Khulna','Jashore','Jhikargacha'),('Khulna','Jashore','Keshabpur'),('Khulna','Jashore','Jessore Sadar'),('Khulna','Jashore','Sharsha'),
('Khulna','Satkhira','Assasuni'),('Khulna','Satkhira','Debhata'),('Khulna','Satkhira','Kalaroa'),('Khulna','Satkhira','Satkhira Sadar'),('Khulna','Satkhira','Shyamnagar'),('Khulna','Satkhira','Tala'),('Khulna','Satkhira','Kaliganj'),
('Khulna','Meherpur','Mujibnagar'),('Khulna','Meherpur','Meherpur Sadar'),('Khulna','Meherpur','Gangni'),
('Khulna','Narail','Narail Sadar'),('Khulna','Narail','Lohagara'),('Khulna','Narail','Kalia'),
('Khulna','Chuadanga','Chuadanga Sadar'),('Khulna','Chuadanga','Alamdanga'),('Khulna','Chuadanga','Damurhuda'),('Khulna','Chuadanga','Jibannagar'),
('Khulna','Kushtia','Kushtia Sadar'),('Khulna','Kushtia','Kumarkhali'),('Khulna','Kushtia','Khoksa'),('Khulna','Kushtia','Mirpur'),('Khulna','Kushtia','Daulatpur'),('Khulna','Kushtia','Bheramara'),
('Khulna','Magura','Shalikha'),('Khulna','Magura','Sreepur'),('Khulna','Magura','Magura Sadar'),('Khulna','Magura','Mohammadpur'),
('Khulna','Khulna','Paikgasa'),('Khulna','Khulna','Fultola'),('Khulna','Khulna','Digholia'),('Khulna','Khulna','Rupsha'),('Khulna','Khulna','Terokhada'),('Khulna','Khulna','Dumuria'),('Khulna','Khulna','Botiaghata'),('Khulna','Khulna','Dakop'),('Khulna','Khulna','Koyra'),
('Khulna','Bagerhat','Fakirhat'),('Khulna','Bagerhat','Bagerhat Sadar'),('Khulna','Bagerhat','Mollahat'),('Khulna','Bagerhat','Sarankhola'),('Khulna','Bagerhat','Rampal'),('Khulna','Bagerhat','Morrelganj'),('Khulna','Bagerhat','Kachua'),('Khulna','Bagerhat','Mongla'),('Khulna','Bagerhat','Chitalmari'),
('Khulna','Jhenaidah','Jhenaidah Sadar'),('Khulna','Jhenaidah','Shailkupa'),('Khulna','Jhenaidah','Harinakundu'),('Khulna','Jhenaidah','Kaliganj'),('Khulna','Jhenaidah','Kotchandpur'),('Khulna','Jhenaidah','Moheshpur'),
('Barisal','Jhalakathi','Jhalakathi Sadar'),('Barisal','Jhalakathi','Kathalia'),('Barisal','Jhalakathi','Nalchity'),('Barisal','Jhalakathi','Rajapur'),
('Barisal','Patuakhali','Bauphal'),('Barisal','Patuakhali','Patuakhali Sadar'),('Barisal','Patuakhali','Dumki'),('Barisal','Patuakhali','Dashmina'),('Barisal','Patuakhali','Kalapara'),('Barisal','Patuakhali','Mirzaganj'),('Barisal','Patuakhali','Galachipa'),('Barisal','Patuakhali','Rangabali'),
('Barisal','Pirojpur','Pirojpur Sadar'),('Barisal','Pirojpur','Nazirpur'),('Barisal','Pirojpur','Kawkhali'),('Barisal','Pirojpur','Zianagar'),('Barisal','Pirojpur','Bhandaria'),('Barisal','Pirojpur','Mathbaria'),('Barisal','Pirojpur','Nesarabad'),
('Barisal','Barisal','Barisal Sadar'),('Barisal','Barisal','Bakerganj'),('Barisal','Barisal','Babuganj'),('Barisal','Barisal','Wazirpur'),('Barisal','Barisal','Banaripara'),('Barisal','Barisal','Gournadi'),('Barisal','Barisal','Agailjhara'),('Barisal','Barisal','Mehendiganj'),('Barisal','Barisal','Muladi'),('Barisal','Barisal','Hizla'),
('Barisal','Bhola','Bhola Sadar'),('Barisal','Bhola','Borhan Sddin'),('Barisal','Bhola','Charfesson'),('Barisal','Bhola','Doulatkhan'),('Barisal','Bhola','Monpura'),('Barisal','Bhola','Tazumuddin'),('Barisal','Bhola','Lalmohan'),
('Barisal','Barguna','Amtali'),('Barisal','Barguna','Barguna Sadar'),('Barisal','Barguna','Betagi'),('Barisal','Barguna','Bamna'),('Barisal','Barguna','Pathorghata'),('Barisal','Barguna','Taltali'),
('Sylhet','Sylhet','Balaganj'),('Sylhet','Sylhet','Beanibazar'),('Sylhet','Sylhet','Bishwanath'),('Sylhet','Sylhet','Companiganj'),('Sylhet','Sylhet','Fenchuganj'),('Sylhet','Sylhet','Golapganj'),('Sylhet','Sylhet','Gowainghat'),('Sylhet','Sylhet','Jaintiapur'),('Sylhet','Sylhet','Kanaighat'),('Sylhet','Sylhet','Sylhet Sadar'),('Sylhet','Sylhet','Zakiganj'),('Sylhet','Sylhet','Dakshinsurma'),('Sylhet','Sylhet','Osmaninagar'),
('Sylhet','Moulvibazar','Barlekha'),('Sylhet','Moulvibazar','Kamolganj'),('Sylhet','Moulvibazar','Kulaura'),('Sylhet','Moulvibazar','Moulvibazar Sadar'),('Sylhet','Moulvibazar','Rajnagar'),('Sylhet','Moulvibazar','Sreemangal'),('Sylhet','Moulvibazar','Juri'),
('Sylhet','Habiganj','Nabiganj'),('Sylhet','Habiganj','Bahubal'),('Sylhet','Habiganj','Ajmiriganj'),('Sylhet','Habiganj','Baniachong'),('Sylhet','Habiganj','Lakhai'),('Sylhet','Habiganj','Chunarughat'),('Sylhet','Habiganj','Habiganj Sadar'),('Sylhet','Habiganj','Madhabpur'),
('Sylhet','Sunamganj','Sunamganj Sadar'),('Sylhet','Sunamganj','South Sunamganj'),('Sylhet','Sunamganj','Bishwambarpur'),('Sylhet','Sunamganj','Chhatak'),('Sylhet','Sunamganj','Jagannathpur'),('Sylhet','Sunamganj','Dowarabazar'),('Sylhet','Sunamganj','Tahirpur'),('Sylhet','Sunamganj','Dharmapasha'),('Sylhet','Sunamganj','Jamalganj'),('Sylhet','Sunamganj','Shalla'),('Sylhet','Sunamganj','Derai'),('Sylhet','Sunamganj','Madhyanagar'),
('Dhaka','Narsingdi','Belabo'),('Dhaka','Narsingdi','Monohardi'),('Dhaka','Narsingdi','Narsingdi Sadar'),('Dhaka','Narsingdi','Palash'),('Dhaka','Narsingdi','Raipura'),('Dhaka','Narsingdi','Shibpur'),
('Dhaka','Gazipur','Kaliganj'),('Dhaka','Gazipur','Kaliakair'),('Dhaka','Gazipur','Kapasia'),('Dhaka','Gazipur','Gazipur Sadar'),('Dhaka','Gazipur','Sreepur'),
('Dhaka','Shariatpur','Shariatpur Sadar'),('Dhaka','Shariatpur','Naria'),('Dhaka','Shariatpur','Zajira'),('Dhaka','Shariatpur','Gosairhat'),('Dhaka','Shariatpur','Bhedarganj'),('Dhaka','Shariatpur','Damudya'),
('Dhaka','Narayanganj','Araihazar'),('Dhaka','Narayanganj','Bandar'),('Dhaka','Narayanganj','Narayanganj Sadar'),('Dhaka','Narayanganj','Rupganj'),('Dhaka','Narayanganj','Sonargaon'),
('Dhaka','Tangail','Basail'),('Dhaka','Tangail','Bhuapur'),('Dhaka','Tangail','Delduar'),('Dhaka','Tangail','Ghatail'),('Dhaka','Tangail','Gopalpur'),('Dhaka','Tangail','Madhupur'),('Dhaka','Tangail','Mirzapur'),('Dhaka','Tangail','Nagarpur'),('Dhaka','Tangail','Sakhipur'),('Dhaka','Tangail','Tangail Sadar'),('Dhaka','Tangail','Kalihati'),('Dhaka','Tangail','Dhanbari'),
('Dhaka','Kishoreganj','Itna'),('Dhaka','Kishoreganj','Katiadi'),('Dhaka','Kishoreganj','Bhairab'),('Dhaka','Kishoreganj','Tarail'),('Dhaka','Kishoreganj','Hossainpur'),('Dhaka','Kishoreganj','Pakundia'),('Dhaka','Kishoreganj','Kuliarchar'),('Dhaka','Kishoreganj','Kishoreganj Sadar'),('Dhaka','Kishoreganj','Karimgonj'),('Dhaka','Kishoreganj','Bajitpur'),('Dhaka','Kishoreganj','Austagram'),('Dhaka','Kishoreganj','Mithamoin'),('Dhaka','Kishoreganj','Nikli'),
('Dhaka','Manikganj','Harirampur'),('Dhaka','Manikganj','Saturia'),('Dhaka','Manikganj','Manikganj Sadar'),('Dhaka','Manikganj','Gior'),('Dhaka','Manikganj','Shibaloy'),('Dhaka','Manikganj','Doulatpur'),('Dhaka','Manikganj','Singiar'),
('Dhaka','Dhaka','Savar'),('Dhaka','Dhaka','Dhamrai'),('Dhaka','Dhaka','Keraniganj'),('Dhaka','Dhaka','Nawabganj'),('Dhaka','Dhaka','Dohar'),
('Dhaka','Munshiganj','Munshiganj Sadar'),('Dhaka','Munshiganj','Sreenagar'),('Dhaka','Munshiganj','Sirajdikhan'),('Dhaka','Munshiganj','Louhajanj'),('Dhaka','Munshiganj','Gajaria'),('Dhaka','Munshiganj','Tongibari'),
('Dhaka','Rajbari','Rajbari Sadar'),('Dhaka','Rajbari','Goalanda'),('Dhaka','Rajbari','Pangsa'),('Dhaka','Rajbari','Baliakandi'),('Dhaka','Rajbari','Kalukhali'),
('Dhaka','Madaripur','Madaripur Sadar'),('Dhaka','Madaripur','Shibchar'),('Dhaka','Madaripur','Kalkini'),('Dhaka','Madaripur','Rajoir'),('Dhaka','Madaripur','Dasar'),
('Dhaka','Gopalganj','Gopalganj Sadar'),('Dhaka','Gopalganj','Kashiani'),('Dhaka','Gopalganj','Tungipara'),('Dhaka','Gopalganj','Kotalipara'),('Dhaka','Gopalganj','Muksudpur'),
('Dhaka','Faridpur','Faridpur Sadar'),('Dhaka','Faridpur','Alfadanga'),('Dhaka','Faridpur','Boalmari'),('Dhaka','Faridpur','Sadarpur'),('Dhaka','Faridpur','Nagarkanda'),('Dhaka','Faridpur','Bhanga'),('Dhaka','Faridpur','Charbhadrasan'),('Dhaka','Faridpur','Madhukhali'),('Dhaka','Faridpur','Saltha'),
('Rangpur','Panchagarh','Panchagarh Sadar'),('Rangpur','Panchagarh','Debiganj'),('Rangpur','Panchagarh','Boda'),('Rangpur','Panchagarh','Atwari'),('Rangpur','Panchagarh','Tetulia'),
('Rangpur','Dinajpur','Nawabganj'),('Rangpur','Dinajpur','Birganj'),('Rangpur','Dinajpur','Ghoraghat'),('Rangpur','Dinajpur','Birampur'),('Rangpur','Dinajpur','Parbatipur'),('Rangpur','Dinajpur','Bochaganj'),('Rangpur','Dinajpur','Kaharol'),('Rangpur','Dinajpur','Fulbari'),('Rangpur','Dinajpur','Dinajpur Sadar'),('Rangpur','Dinajpur','Hakimpur'),('Rangpur','Dinajpur','Khansama'),('Rangpur','Dinajpur','Birol'),('Rangpur','Dinajpur','Chirirbandar'),
('Rangpur','Lalmonirhat','Lalmonirhat Sadar'),('Rangpur','Lalmonirhat','Kaliganj'),('Rangpur','Lalmonirhat','Hatibandha'),('Rangpur','Lalmonirhat','Patgram'),('Rangpur','Lalmonirhat','Aditmari'),
('Rangpur','Nilphamari','Syedpur'),('Rangpur','Nilphamari','Domar'),('Rangpur','Nilphamari','Dimla'),('Rangpur','Nilphamari','Jaldhaka'),('Rangpur','Nilphamari','Kishorganj'),('Rangpur','Nilphamari','Nilphamari Sadar'),
('Rangpur','Gaibandha','Sadullapur'),('Rangpur','Gaibandha','Gaibandha Sadar'),('Rangpur','Gaibandha','Palashbari'),('Rangpur','Gaibandha','Saghata'),('Rangpur','Gaibandha','Gobindaganj'),('Rangpur','Gaibandha','Sundarganj'),('Rangpur','Gaibandha','Phulchari'),
('Rangpur','Thakurgaon','Thakurgaon Sadar'),('Rangpur','Thakurgaon','Pirganj'),('Rangpur','Thakurgaon','Ranisankail'),('Rangpur','Thakurgaon','Haripur'),('Rangpur','Thakurgaon','Baliadangi'),
('Rangpur','Rangpur','Rangpur Sadar'),('Rangpur','Rangpur','Gangachara'),('Rangpur','Rangpur','Taragonj'),('Rangpur','Rangpur','Badargonj'),('Rangpur','Rangpur','Mithapukur'),('Rangpur','Rangpur','Pirgonj'),('Rangpur','Rangpur','Kaunia'),('Rangpur','Rangpur','Pirgacha'),
('Rangpur','Kurigram','Kurigram Sadar'),('Rangpur','Kurigram','Nageshwari'),('Rangpur','Kurigram','Bhurungamari'),('Rangpur','Kurigram','Phulbari'),('Rangpur','Kurigram','Rajarhat'),('Rangpur','Kurigram','Ulipur'),('Rangpur','Kurigram','Chilmari'),('Rangpur','Kurigram','Rowmari'),('Rangpur','Kurigram','Charrajibpur'),
('Mymensingh','Sherpur','Sherpur Sadar'),('Mymensingh','Sherpur','Nalitabari'),('Mymensingh','Sherpur','Sreebordi'),('Mymensingh','Sherpur','Nokla'),('Mymensingh','Sherpur','Jhenaigati'),
('Mymensingh','Mymensingh','Fulbaria'),('Mymensingh','Mymensingh','Trishal'),('Mymensingh','Mymensingh','Bhaluka'),('Mymensingh','Mymensingh','Muktagacha'),('Mymensingh','Mymensingh','Mymensingh Sadar'),('Mymensingh','Mymensingh','Dhobaura'),('Mymensingh','Mymensingh','Phulpur'),('Mymensingh','Mymensingh','Haluaghat'),('Mymensingh','Mymensingh','Gouripur'),('Mymensingh','Mymensingh','Gafargaon'),('Mymensingh','Mymensingh','Iswarganj'),('Mymensingh','Mymensingh','Nandail'),('Mymensingh','Mymensingh','Tarakanda'),
('Mymensingh','Jamalpur','Jamalpur Sadar'),('Mymensingh','Jamalpur','Melandah'),('Mymensingh','Jamalpur','Islampur'),('Mymensingh','Jamalpur','Dewangonj'),('Mymensingh','Jamalpur','Sarishabari'),('Mymensingh','Jamalpur','Madarganj'),('Mymensingh','Jamalpur','Bokshiganj'),
('Mymensingh','Netrokona','Barhatta'),('Mymensingh','Netrokona','Durgapur'),('Mymensingh','Netrokona','Kendua'),('Mymensingh','Netrokona','Atpara'),('Mymensingh','Netrokona','Madan'),('Mymensingh','Netrokona','Khaliajuri'),('Mymensingh','Netrokona','Kalmakanda'),('Mymensingh','Netrokona','Mohongonj'),('Mymensingh','Netrokona','Purbadhala'),('Mymensingh','Netrokona','Netrokona Sadar')
ON CONFLICT (division, district, upazila) DO NOTHING;